//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolDataEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LolDataEntities : DbContext
    {
        public LolDataEntities()
            : base("name=LolDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<allaero> allaero { get; set; }
        public DbSet<allchampion> allchampion { get; set; }
        public DbSet<gametype> gametype { get; set; }
        public DbSet<maptype> maptype { get; set; }
        public DbSet<tierqueue> tierqueue { get; set; }
        public DbSet<winorlose> winorlose { get; set; }
        public DbSet<aero_census> aero_census { get; set; }
        public DbSet<game_tag> game_tag { get; set; }
        public DbSet<hero_info> hero_info { get; set; }
        public DbSet<hero_trend> hero_trend { get; set; }
        public DbSet<receive_feedback> receive_feedback { get; set; }
        public DbSet<receive_mail> receive_mail { get; set; }
        public DbSet<web_log> web_log { get; set; }
        public DbSet<website_info> website_info { get; set; }
    }
}
