//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolDataEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class receive_feedback
    {
        public long Id { get; set; }
        public string C_Name_ { get; set; }
        public int Sex { get; set; }
        public string Type { get; set; }
        public string Context { get; set; }
        public string QQ { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public System.DateTime ReceiveTime { get; set; }
    }
}
