//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolDataEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_log
    {
        public long Id { get; set; }
        public string Log { get; set; }
        public System.DateTime LogTime { get; set; }
        public string LogFrom { get; set; }
        public string C_LogType_ { get; set; }
    }
}
