//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolDataEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class website_info
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public int Count_num { get; set; }
        public System.DateTime LastUpdataTime { get; set; }
    }
}
