//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolDataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class allaero
    {
        public int Id { get; set; }
        public string StrId { get; set; }
        public string Isp { get; set; }
        public string AeroName { get; set; }
        public string Idc { get; set; }
        public int Tcls { get; set; }
        public int Ob { get; set; }
    }
}
