//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolDataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class allchampion
    {
        public int Id { get; set; }
        public string Ename { get; set; }
        public string Title { get; set; }
        public string Cname { get; set; }
        public string Pic { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
