//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolDataDb
{
    using MySql.Data.Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    [DbConfigurationType(typeof(MySqlEFConfiguration))]
    public partial class loldataEntities : DbContext
    {
        public loldataEntities()
            : base("name=loldataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aero_census> aero_census { get; set; }
        public virtual DbSet<allaero> allaero { get; set; }
        public virtual DbSet<allchampion> allchampion { get; set; }
        public virtual DbSet<game_tag> game_tag { get; set; }
        public virtual DbSet<gametype> gametype { get; set; }
        public virtual DbSet<hero_info> hero_info { get; set; }
        public virtual DbSet<hero_trend> hero_trend { get; set; }
        public virtual DbSet<maptype> maptype { get; set; }
        public virtual DbSet<receive_feedback> receive_feedback { get; set; }
        public virtual DbSet<receive_mail> receive_mail { get; set; }
        public virtual DbSet<tierqueue> tierqueue { get; set; }
        public virtual DbSet<website_info> website_info { get; set; }
        public virtual DbSet<winorlose> winorlose { get; set; }
        public virtual DbSet<web_log> web_log { get; set; }
    }
}
