//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolDataDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class receive_mail
    {
        public long Id { get; set; }
        public string MailSubject { get; set; }
        public string MailContext { get; set; }
        public System.DateTime ReceiveTime { get; set; }
        public string FeedBackMailAddress { get; set; }
    }
}
